### ISSUE TITLE
Spinner callback called during initialization

### ISSUE THREAD

**Issue by EduModsS** [commonuserlol/frida-java-menu#2]
How to start with this?, after install it. what i need to do? where do I put the file to build like (frida-compile myconpilefile -o mycompiledfile -c

**Comment by EduModsS** [comment]
I managed to make it work, just the functions didn't lol


- I couldn't use a base64 image, only Web worked
this code:


let menu = new Menu.JavaMenu("EduMods", "", Menu.Theme.LGL);
	menu.icon("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1UUmAqmf8y8H92AFY_wf4Ij0o-RGJjPdseA&usqp=CAU", "Web");

	menu.add(Menu.textView("Label"));

	menu.show();

after add the menu.add (anything) it always error: Error: java.lang.IllegalArgumentException: View=android.widget.FrameLayout{6218d32 G.E...... ......I. 0,0-0,0} not attached to window manager

**Comment by commonuserlol** [comment]
More details? android version? when does this occur? your code, etc.

**Comment by EduModsS** [comment]
the mistake was because I were doing it wrong lol, I got confused seeing the examples, but after a while I managed to fix it.

**Comment by EduModsS** [comment]
I saw a function, called alert, how to use it?

**Comment by EduModsS** [comment]
I saw a function called [ async dialog(title, message, positiveCallback, negativeCallback, view) ] how to use ? give an example

**Comment by EduModsS** [comment]
Ah, I had made an error, I modified it and fixed it. it's in spinner(items, callback) function, in if (callback) its not defined to call the function, and ele está vindo sempre ativo (ex: (t)=>{log(t);}); As soon as I open the menu it activates, even without even touching the menu

**Comment by commonuserlol** [comment]
> I saw a function called [ async dialog(title, message, positiveCallback, negativeCallback, view) ] how to use ? give an example

```typescript
menu.button("asd", () => {
    menu.dialog("Title", "Cool message", () => toast("this will be shown when user press positive button"), () => toast("this will be shown when user press negative button"));
});
```
Buttons labels defined in `Theme.LGL`, if you want change them you can create own theme by `new Menu.Theme();` or
```typescript
let myTheme = Menu.Theme.LGL;
myTheme.property = ...;
```

**Comment by commonuserlol** [comment]
> As soon as I open the menu it activates, even without even touching the menu

Yes because it restores previous value. Should i add option to turn off this feature?

**Comment by EduModsS** [comment]
> > As soon as I open the menu it activates, even without even touching the menu
> 
> Yes because it restores previous value. Should i add option to turn off this feature?

I say like, I had to modify the code for the callback function, and I want to say something like: when I open the menu (first time I open it) it does the of function Even if I don't do anything then, I think I should check if it's the first time opening the menu or not

**Comment by commonuserlol** [comment]
So if you not touched, it still calls callback with index 0?

**Comment by EduModsS** [comment]
yes, it makes callback with index 0

**Comment by EduModsS** [comment]
it just does this callback, when I open the menu for the first time if I'm not mistaken, the second / third time nothing happens (unless I touch and change to other)

**Comment by commonuserlol** [comment]
No idea actually... Spinner by default have -1 value (why?) and since -1 not allowed it will use 0 and change state
Does original LGL have same behavior?

**Comment by commonuserlol** [comment]
Alright i fixed that in https://github.com/commonuserlol/frida-java-menu/commit/f1b192aadf3472c2328c34eb4bd5ce4cc0be4670. As google says, it's even android bug, so solution taken from https://stackoverflow.com/questions/13397933/android-spinner-avoid-onitemselected-calls-during-initialization/69367698#69367698
Reopen if not worked or smth
