### ISSUE TITLE
I'm not able to install

### ISSUE THREAD

**Issue by EduModsS** [commonuserlol/frida-java-menu#21]
I'm using "npm i git+https://github.com/commonuserlol/frida-java-menu/" in the project, but there is an error:

.../home/FRIDA-AGENT $ npm i git+https://github.com/commonuserlol/frida-java-menu/
npm ERR! code 2
npm ERR! git dep preparation failed
npm ERR! command /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/data/data/com.termux/files/home/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > frida-java-menu@2.0.1 prepare
npm ERR! > tsc
npm ERR!
npm ERR! node_modules/@types/frida-gum/index.d.ts(2699,15): error TS2300: Duplicate identifier 'File'.
npm ERR! ../../../../node_modules/@types/node/globals.d.ts(405,15): error TS2300: Duplicate identifier 'File'.
npm ERR! ../../../../node_modules/@types/node/globals.d.ts(406,9): error TS2300: Duplicate identifier 'File'.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 2
npm ERR! npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/git-cloneqBmz6mbJAhd6
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c tsc
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-03-03T17_35_26_859Z-debug-0.log

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-03-03T17_35_23_100Z-debug-0.log

**Comment by commonuserlol** [comment]
Does your frida agent have tsconfig.json? Probably your `lib` key have `dom` value or not defined at all

**Comment by EduModsS** [comment]
it has tsconfig, which I generated with tsc --init (I didn't modify anything inside tsconfig, after generating)

**Comment by EduModsS** [comment]
lib is not defined, what should I put? // "lib": []

**Comment by commonuserlol** [comment]
If you delete it (tsconfig), will module install correctly ?

**Comment by EduModsS** [comment]
before installing tsconfig it was giving errors too

**Comment by commonuserlol** [comment]
Gimme 10m to test on termux

**Comment by commonuserlol** [comment]
Try clearing npm cache or smth, my phone is ok (aarch64, but i don't think that it matter)
![img](https://github.com/commonuserlol/frida-java-menu/assets/111648021/75991ab1-799f-4777-a47b-d89ca599fbf8)

**Comment by EduModsS** [comment]
I tried everything and it didn't work, I cleaned all the termux data and redid all the installations and it worked now, thanks
