### ISSUE TITLE
how i can add two floating menu?

### ISSUE THREAD

**Issue by EduModsS** [commonuserlol/frida-java-menu#23]
one normal with the layout and the other with a custom callback?

like

```
const composer2 = new Menu.Composer("title", "subtitle", layout, true);
composer2.icon(...);
composer2.onIconClick(callBack);
composer2.show();


const composer = ...
```

and show? or, add via a button?

like
```
const composer2 = new Menu.Composer("title", "subtitle", layout, true);

let idk = layout.toggle("idk", (state) => {
		if (state)
                    composer2.icon(...);
                    composer2.onIconClick(callBack);
                    composer2.show();
                else
                     composer2.destroy();
});
```

**Comment by EduModsS** [comment]
I'm asking because when I use two composers, the menu gets bugged and none of them appear

**Comment by EduModsS** [comment]
Forget about that, I managed to do both floating

**Comment by commonuserlol** [comment]
ah I didn't saw that issue, why you need 2?

**Comment by EduModsS** [comment]
I wanted to do something similar to what I saw in another lgl mod, where there were two floating ones, but I found something to improvise it lol

**Comment by EduModsS** [comment]
Did you see what I did, to correct my other mistake? the layout.alert error does not appear

**Comment by commonuserlol** [comment]
Hey, this was designed only for **one** menu.
