### ISSUE TITLE
menu working but toggle has an issue 

### ISSUE THREAD

**Issue by VAROME** [commonuserlol/frida-java-menu#3]
ok, so far it is working and showing ,
i face the issue of off the toggle ,
default is off and no error
i on it , it works
i off it, it error >
[::Gadget ]-> il2cpp: couldn't set implementation for method get_Diamond as it has already been replaced by a thunk
code :
```
 if (state==true ) {
return 131512;
};

 else    
   {
    let value =   this.method("get_Diamond").invoke();

   return value;
  };

```
so how to make  a working on / off toggle to return the value default when off ?

**Comment by EduModsS** [comment]
That's not his problem, it's how you're using it, try hmm... get the implementation beforehand, and when activated it checks the method. and if you disable this returns default return (this.method("").invoke(...methodArg);)

**Comment by commonuserlol** [comment]
You should do something like
```typescript
function myCallback() {
    method.revert();
    if (state) {
        method.implementation = ...
    }
}
```
e.g add revert to exclude errors
