### ISSUE TITLE
it was working but now it does not , frida no root objection

### ISSUE THREAD

**Issue by VAROME** [commonuserlol/frida-java-menu#4]
i know it is partially related to you but you have EXP in that 🥇  ❤️ 
i once did this 
- created working tested JS script that changes game currency 
- used orignal apk 
- confg file
```
{
  "interaction": {
    "type": "script",
    "path": "libfrida-gadget.script.so",
    "on_load": "resume"
  }
}
```
then 

`objection patchapk -s apk.apk -c config.json -l index.js --architecture armeabi-v7a
`
after that to make it on non rooted i did
config2 

```
{
  "interaction": {
    "type": "listen",
    "address": "127.0.0.1",
    "port": 27042,
    "on_load": "resume"
  }
}
```

and then 
`objection patchapk -s apk.objection.apk -c config2.json --architecture armeabi-v7a
`
then it was working , 
now it does not , even i tried a simple working one and all
so how to make a non rooted apk with that script i created ? since objection does not really work now !

- one more thing , 
- the objecton thing, after that the game runs , but not working the script itself , but if i open the gadget frida thing from pc i inject normally the script from pc and runs normally , but not the one that has already been injected, so objection makes the apk run gadget without pausing but at the same time it does not run the script . yet accepts from the PC any script again , or any code to run like without objection

**Comment by commonuserlol** [comment]
Please recreate issue with filled template for bug
I need more info

**Comment by VAROME** [comment]
> Please recreate issue with filled template for bug I need more info

no, there is no template no nothing, this should work with any JS script , template or not , 
like even a return 999 for currency , this worked before, 
this was the reference of it 
https://[github.com/kylesmile1103/Learn-Frida](https://github.com/kylesmile1103/Learn-Frida)

**Comment by VAROME** [comment]
> Issue template means ![Screenshot_20230919_180416](https://user-images.githubusercontent.com/111648021/269003580-de942ad0-9d89-4f30-a9c5-aeb1cf0aeab9.png) ![Screenshot_20230919_180438](https://user-images.githubusercontent.com/111648021/269003612-b914a45e-2ea5-487e-b0f3-e3d145e13a6c.png)
> 
> But okay, provide me info about android version, rom (custom or stock, like MIUI, ColorOS, etc) and app package name/link

bro, i am telling you , it worked for all games, all androids everythng and all , but now it does not , on any game , any phone , nothing, 
you dont need more info cause anything you try on it results the same
